services:
  flight-db:
    image: postgres:16-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flight-app
    restart: unless-stopped

  flight-backend:
    image: ${IMAGE_NAME_BACKEND:-flight-backend}:latest
    container_name: flight-backend
    ports:
      - "127.0.0.1:8010:8010"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - flight-app
    depends_on:
      - flight-db
    restart: unless-stopped

  flight-frontend:
    image: ${IMAGE_NAME_FRONTEND:-flight-frontend}:latest
    container_name: flight-frontend
    ports:
      - "127.0.0.1:3010:3010"
    networks:
      - flight-app
    depends_on:
      - flight-backend
    restart: unless-stopped

networks:
  flight-app:
    name: flight-app
    external: false

volumes:
  postgres_data:
