"""Add Google Drive Sync tables

Revision ID: 003
Revises: 058826f658d0
Create Date: 2026-04-21 15:30:00.000000

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '058826f658d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_google_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('root_folder_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_google_tokens_id'), 'user_google_tokens', ['id'], unique=False)

    op.create_table('google_drive_sync',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('google_folder_id', sa.String(), nullable=False),
    sa.Column('sync_source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_google_drive_sync_google_folder_id'), 'google_drive_sync', ['google_folder_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_drive_sync_google_folder_id'), table_name='google_drive_sync')
    op.drop_table('google_drive_sync')
    op.drop_index(op.f('ix_user_google_tokens_id'), table_name='user_google_tokens')
    op.drop_table('user_google_tokens')
    # ### end Alembic commands ###
